export function generateItems(array: Array<{ country: String, city: String}>) {
    array.push({country:"Afghanistan",city:"Kabul"})
    array.push({country:"Albania", city:"Tirana"})
    array.push({country:"Algeria",city:"Algiers"})
    array.push({country:"Andorra",city:"Andorra la Vella"})
    array.push({country:"Angola",city:"Luanda"})
    array.push({country:"Antigua & Barbuda",city:"Saint John's"})
    array.push({country:"Argentina",city:"Buenos Aires"})
    array.push({country:"Armenia",city:"Yerevan"})
    array.push({country:"Australia",city:"Canberra"})
    array.push({country:"Austria",city:"Vienna"})
    array.push({country:"Azerbaijan",city:"Baku"})
    array.push({country:"Bahamas",city:"Nassau"})
    array.push({country:"Bahrain",city:"Manama"})
    array.push({country:"Bangladesh",city:"Dhaka"})
    array.push({country:"Barbados",city:"Bridgetown"})
    array.push({country:"Belarus",city:"Minsk"})
    array.push({country:"Belgium",city:"Brussels"})
    array.push({country:"Belize",city:"Belmopan"})
    array.push({country:"Benin",city:"Porto Novo"})
    array.push({country:"Bhutan",city:"Thimphu"})
    array.push({country:"Bolivia, admin.",city:"La Paz"})
    array.push({country:"Bolivia, offic.",city:"Sucre"})
    array.push({country:"Bosnia & Herzegovina",city:"Sarajevo"})
    array.push({country:"Botswana",city:"Gaborone"})
    array.push({country:"Brazil",city:"Brasilia"})
    array.push({country:"Brunei",city:"Bandar Seri Begawan"})
    array.push({country:"Bulgaria",city:"Sofia"})
    array.push({country:"Burkina Faso",city:"Ouagadougou"})
    array.push({country:"Burundi",city:"Gitega"})
    array.push({country:"Cambodia",city:"Phnom Penh"})
    array.push({country:"Cameroon",city:"Yaounde"})
    array.push({country:"Canada",city:"Ottawa"})
    array.push({country:"Cape Verde",city:"Praia"})
    array.push({country:"Central African Rep.",city:"Bangui"})
    array.push({country:"Chad",city:"N'Djamena"})
    array.push({country:"Chile",city:"Santiago"})
    array.push({country:"China",city:"Beijing"})
    array.push({country:"Colombia",city:"Bogota"})
    array.push({country:"Comoros",city:"Moroni"})
    array.push({country:"Congo, Dem. Rep.",city:"Kinshasa"})
    array.push({country:"Congo, Rep.",city:"Brazzaville"})
    array.push({country:"Costa Rica",city:"San Jose"})
    array.push({country:"Cote d'Ivoire",city:"Yamoussoukro"})
    array.push({country:"Croatia",city:"Zagreb"})
    array.push({country:"Cuba",city:"Havana"})
    array.push({country:"Cyprus",city:"Nicosia"})
    array.push({country:"Czech Republic",city:"Prague"})
    array.push({country:"Denmark",city:"Copenhagen"})
    array.push({country:"Djibouti",city:"Djibouti"})
    array.push({country:"Dominica",city:"Roseau"})
    array.push({country:"Dominican Rep.",city:"Santo Domingo"})
    array.push({country:"East Timor",city:"Dili"})
    array.push({country:"Ecuador",city:"Quito"})
    array.push({country:"Egypt",city:"Cairo"})
    array.push({country:"El Salvador",city:"San Salvador"})
    array.push({country:"England",city:"London"})
    array.push({country:"Equatorial Guinea",city:"Malabo"})
    array.push({country:"Eritrea",city:"Asmara"})
    array.push({country:"Estonia",city:"Tallinn"})
    array.push({country:"Eswatini",city:"Mbabana"})
    array.push({country:"Ethiopia",city:"Addis Ababa"})
    array.push({country:"Fed. St. of Micronesia",city:"Palikir"})
    array.push({country:"Fiji",city:"Suva"})
    array.push({country:"Finland",city:"Helsinki"})
    array.push({country:"France",city:"Paris"})
    array.push({country:"Gabon",city:"Libreville"})
    array.push({country:"Gambia",city:"Banjul"})
    array.push({country:"Georgia",city:"Tbilisi"})
    array.push({country:"Germany",city:"Berlin"})
    array.push({country:"Ghana",city:"Accra"})
    array.push({country:"Greece",city:"Athens"})
    array.push({country:"Grenada",city:"Saint George's"})
    array.push({country:"Guatemala",city:"Guatemala City"})
    array.push({country:"Guinea",city:"Conakry"})
    array.push({country:"Guinea-Bissau",city:"Bissau"})
    array.push({country:"Guyana",city:"Georgetown"})
    array.push({country:"Haiti",city:"Port au Prince"})
    array.push({country:"Honduras",city:"Tegucigalpa"})
    array.push({country:"Hungary",city:"Budapest"})
    array.push({country:"Iceland",city:"Reykjavik"})
    array.push({country:"India",city:"New Delhi"})
    array.push({country:"Indonesia",city:"Jakarta"})
    array.push({country:"Iran",city:"Tehran"})
    array.push({country:"Iraq",city:"Baghdad"})
    array.push({country:"Ireland",city:"Dublin"})
    array.push({country:"Israel",city:"Jerusalem"})
    array.push({country:"Italy",city:"Rome"})
    array.push({country:"Jamaica",city:"Kingston"})
    array.push({country:"Japan",city:"Tokyo"})
    array.push({country:"Jordan",city:"Amman"})
    array.push({country:"Kazakhstan",city:"Astana"})
    array.push({country:"Kenya",city:"Nairobi"})
    array.push({country:"Kiribati",city:"Tarawa Atoll"})
    array.push({country:"Kosovo",city:"Pristina"})
    array.push({country:"Kuwait",city:"Kuwait City"})
    array.push({country:"Kyrgyzstan",city:"Bishkek"})
    array.push({country:"Laos",city:"Vientiane"})
    array.push({country:"Latvia",city:"Riga"})
    array.push({country:"Lebanon",city:"Beirut"})
    array.push({country:"Lesotho",city:"Maseru"})
    array.push({country:"Liberia",city:"Monrovia"})
    array.push({country:"Libya",city:"Tripoli"})
    array.push({country:"Liechtenstein",city:"Vaduz"})
    array.push({country:"Lithuania",city:"Vilnius"})
    array.push({country:"Luxembourg",city:"Luxembourg"})
    array.push({country:"Madagascar",city:"Antananarivo"})
    array.push({country:"Malawi",city:"Lilongwe"})
    array.push({country:"Malaysia",city:"Kuala Lumpur"})
    array.push({country:"Maldives",city:"Male"})
    array.push({country:"Mali",city:"Bamako"})
    array.push({country:"Malta",city:"Valletta"})
    array.push({country:"Marshall Islands",city:"Majuro"})
    array.push({country:"Mauritania",city:"Nouakchott"})
    array.push({country:"Mauritius",city:"Port Louis"})
    array.push({country:"Mexico",city:"Mexico City"})
    array.push({country:"Moldova",city:"Chisinau"})
    array.push({country:"Monaco",city:"Monaco"})
    array.push({country:"Mongolia",city:"Ulaanbaatar"})
    array.push({country:"Montenegro",city:"Podgorica"})
    array.push({country:"Morocco",city:"Rabat"})
    array.push({country:"Mozambique",city:"Maputo"})
    array.push({country:"Myanmar",city:"Nay Pyi Taw"})
    array.push({country:"Namibia",city:"Windhoek"})
    array.push({country:"Nauru",city:"-"})
    array.push({country:"Nepal",city:"Kathmandu"})
    array.push({country:"Netherlands",city:"Amsterdam"})
    array.push({country:"New Zealand",city:"Wellington"})
    array.push({country:"Nicaragua",city:"Managua"})
    array.push({country:"Niger",city:"Niamey"})
    array.push({country:"Nigeria",city:"Abuja"})
    array.push({country:"North Korea",city:"Pyongyang"})
    array.push({country:"North Macedonia",city:"Skopje"})
    array.push({country:"Northern Ireland",city:"Belfast"})
    array.push({country:"Norway",city:"Oslo"})
    array.push({country:"Oman",city:"Muscat"})
    array.push({country:"Pakistan",city:"Islamabad"})
    array.push({country:"Palau",city:"Melekeok"})
    array.push({country:"Palestine",city:"Jerusalem"})
    array.push({country:"Panama",city:"Panama City"})
    array.push({country:"Papua New Guinea",city:"Port Moresby"})
    array.push({country:"Paraguay",city:"Asuncion"})
    array.push({country:"Peru",city:"Lima"})
    array.push({country:"Philippines",city:"Manila"})
    array.push({country:"Poland",city:"Warsaw"})
    array.push({country:"Portugal",city:"Lisbon"})
    array.push({country:"Qatar",city:"Doha"})
    array.push({country:"Romania",city:"Bucharest"})
    array.push({country:"Russia",city:"Moscow"})
    array.push({country:"Rwanda",city:"Kigali"})
    array.push({country:"Saint Kitts & Nevis",city:"Basseterre"})
    array.push({country:"Saint Lucia",city:"Castries"})
    array.push({country:"Saint Vincent & Gren.",city:"Kingstown"})
    array.push({country:"Samoa",city:"Apia"})
    array.push({country:"San Marino",city:"San Marino"})
    array.push({country:"Sao Tome & Principe",city:"Sao Tome"})
    array.push({country:"Sudi Arabia",city:"Riyadh"})
    array.push({country:"Scotland",city:"Edinburgh"})
    array.push({country:"Senegal",city:"Dakar"})
    array.push({country:"Serbia",city:"Belgrade"})
    array.push({country:"Seychelles",city:"Victoria"})
    array.push({country:"Sierra Leone",city:"Freetown"})
    array.push({country:"Singapore",city:"Singapore"})
    array.push({country:"Slovakia",city:"Bratislava"})
    array.push({country:"Slovenia",city:"Ljubljana"})
    array.push({country:"Solomon Islans",city:"Honiara"})
    array.push({country:"Somalia",city:"Mogadishu"})
    array.push({country:"South Africa, admin.",city:"Pretoria"})
    array.push({country:"South Africa, legis.",city:"Cape Town"})
    array.push({country:"South Africa, judic.",city:"Bloemfontein"})
    array.push({country:"South Korea",city:"Seoul"})
    array.push({country:"South Sudan",city:"Juba"})
    array.push({country:"Spain",city:"Madrid"})
    array.push({country:"Sri Lanka",city:"Sri Jayaw. Kotte"})
    array.push({country:"Sudan",city:"Khartoum"})
    array.push({country:"Suriname",city:"Paramaribo"})
    array.push({country:"Sweden",city:"Stockholm"})
    array.push({country:"Switzerland",city:"Bern"})
    array.push({country:"Syria",city:"Damascus"})
    array.push({country:"Taiwan",city:"Taipei"})
    array.push({country:"Tajikistan",city:"Dushanbe"})
    array.push({country:"Tanzania",city:"Dodoma"})
    array.push({country:"Thailand",city:"Bangkok"})
    array.push({country:"Togo",city:"Lome"})
    array.push({country:"Tonga",city:"Nuku'alofa"})
    array.push({country:"Trinidad & Toboga",city:"Port of Spain"})
    array.push({country:"Tunisia",city:"Tunis"})
    array.push({country:"Turkey",city:"Ankara"})
    array.push({country:"Turkmenistan",city:"Ashgabat"})
    array.push({country:"Tuvalu",city:"Funafuti"})
    array.push({country:"Uganda",city:"Kampala"})
    array.push({country:"Ukraine",city:"Kiev"})
    array.push({country:"United Arab Emirates",city:"Abu Dhabi"})
    array.push({country:"United Kingdom",city:"London"})
    array.push({country:"United States",city:"Washington D.C."})
    array.push({country:"Uruguay",city:"Montevideo"})
    array.push({country:"Uzbekistan",city:"Tashkent"})
    array.push({country:"Vanuatu",city:"Port Vila"})
    array.push({country:"Vatican City",city:"Vatican City"})
    array.push({country:"Venezuela",city:"Caracas"})
    array.push({country:"Vietnam",city:"Hanoi"})
    array.push({country:"Wales",city:"Cardiff"})
    array.push({country:"Yemen",city:"Sana'a"})
    array.push({country:"Zambia",city:"Lusaka"})
    array.push({country:"Zimbabwe",city:"Harare"})
}